server:
  port: 14520

## 开启swagger的basic认证功能
swagger:
  basic:
    enable: true
    ##认证用户名
    username: Jaywatson
    ##认证密码
    password: 123456

# 数据库访问配置
# 主数据源，默认的
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    #driver-class-name自动配置为com.mysql.cj.jdbc.Driver,无需额外配置
    #driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://106.14.220.77:3306/technology_online?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    druid:
      # 初始化大小，最小，最大
      initialSize: 5
      minIdle: 5
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      #验证数据库连接
      validationQuery: select 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters:
        commons-log.connection-logger-name: stat,wall,log4j2
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # 合并多个DruidDataSource的监控数据
      useGlobalDataSourceStat: true
      # 配置监控服务器
      stat-view-servlet:
        login-username: admin
        login-password: 123456
        reset-enable: false
        url-pattern: /druid/*
        # 添加IP白名单
        #allow:
        # 添加IP黑名单，当白名单和黑名单重复时，黑名单优先级更高
        #deny:
      web-stat-filter:
        # 添加过滤规则
        url-pattern: /*
        # 忽略过滤格式
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"

#mybatis-plus配置
mybatis-plus:
  #mapper扫描位置
  mapper-locations: classpath*:com/learning/**/*Mapper.xml,classpath*:com/learning/**/*.mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.learning.**.pojo,com.learning.**.pojo.dto,com.learning.**.pojo.po
  global-config:
    db-config:
      #驼峰下划线转换
      table-underline: true
      db-column-underline: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl


#SM.MS图床
sm:
  url: https://sm.ms/api/v2
  token: pesfGnnDjWBB7BD9Dzbn8fRzGCdFcFYx