server:
  port: 18080

spring:
  datasource:
    name:
    url: jdbc:mysql://106.14.220.77:3306/test?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=UTC
    username: root
    password: 123456

mybatis:
  mapper-locations: classpath:*/mapper/*.xml
